---
author: "Anne Bakker"
date: "2023-11-20"
output: html_document
editor_options: 
  markdown: 
    wrap: sentence
---

# Vrije ruimte

## Interessante onderwerpen

**Neurogenomica:**

\- Integratie van genomics en neurobiologie om de genetische basis van complex gedrag bij dieren te ontrafelen.

\- Analyse van genexpressiegegevens in de hersenen van dieren in relatie tot specifiek gedrag.

**Neuro-informatica voor gedragsanalyse:**

\- Het leren toepassen van machine learning technieken om te voorspellen of een grijppoging binnen een pellet reaching test succesvol of mislukt is.

**Single-Cell Transcriptomics in Tumorbiologie:**

\- Gebruik van single-cell RNA-sequencing om de heterogeniteit van tumorcellen op moleculair niveau te begrijpen.

\- Data science-methoden toepassen om patronen in de expressieprofielen van individuele tumorcellen te identificeren.

**Evolutie van Tumorcellen:**

\- Studie naar de evolutionaire dynamiek van tumorcellen en het ontstaan van subclones.

\- Data science voor het modelleren van tumorcel-evolutie op basis van sequentiegegevens.

**Interactie tussen Tumor en Microbioom:**

\- Onderzoek naar de rol van het microbioom in de tumormicro-omgeving.

\- Data science-analyse van microbiële samenstelling en interacties in relatie tot tumorontwikkeling.

## Uiteindelijke keuze voor vrije ruimte

Ik wil graag leren toepassen van een machine learning techniek om te voorspellen of een grijppoging binnen een pellet reaching test succesvol of mislukt is. Dit komt omdat ik afgelopen jaar stage heb gelopen bij het UMC Utrecht waarbij ik de gedragsanalyse van de Pellet Reaching Test heb uitgvoerd. Hierbij heb ik handmatig alle video's van alle grijppogingen moeten bekijken en moeten labelen als succesvol of mislukt. Dit kostte veel tijd en zou daarom makkelijker kunnen via machine learning. Daarom lijkt het mij interessant om dit te leren in de vrije ruimte.

De data die ik gebruik hiervoor is de data die ik heb verkregen binnen mijn stage bij het UMC Utrecht. 


## Software & packages

Ik wil het gaan uitvoeren in R. Met de verschillende packages: 
`"av"`
`"Magick"`
`"tidymodels"`


## Vrije keuze tijdsplanning

**Dag 1:**

\- 3 uur: Onderzoek doen naar hoe machine learning werkt

\- 5 uur: Data verzamelen en handmatig labelen met succesvol of mislukt.


**Dag 2:**

\- 2 uur: Video's opdelen in verschillende frames

\- 4 uur: Bekijk de packages tidymodels en magick en bekijke oefen opgaves van deze packages 

\- 2 uur: Schrijf Het R script voor het model


**Dag 3:**

\- 2 uur: Schrijf verder aan het R script voor het model

\- 6 uur: Train het model met verschillende datasets die verkregen zijn


**Dag 4:**

\- 5 uur: Maak script voor het voorspellen van en dataset

\- 2 uur: Voer het model uit op verschillende datasets

\- 1 uur: Discussie punten




## Plan

Mijn plan is om machine learning toe te passen op datasets die ik verkregen heb uit mijn stageperiode. Ik leer mijzelf iets volledigs nieuws aan. Tijdens mijn stage heb ik alle data analyse handmatig gedaan, en heb ik elke video zelf moeten kijken om te achterhalen of het om een succesvolle of mislukte grijppoging ging. Door deze machine learning toe te passen wil ik dit vermijden en hopelijk de data analyse in het vervolg sneller te laten verlopen.


## Uitwerking
De uitwerking van mijn vrije opdracht zijn te vinden binnen mijn repository `portfolio` onder "VrijeOpdracht". Het gaat om 2 scripts genaamd `model_maken.R` en `video_frames_labelen.R` die met de ruwe data binnen deze map zal werken.

